/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package application;

import java.sql.DriverManager;
import java.sql.SQLException;

public class App {
    public String getGreeting() {
        return "Hello World! from S05_T46-T51";
    }

    public static void main(String[] args) throws ClassNotFoundException, SQLException {
        System.out.println(new App().getGreeting());
        
        int [] ids = {0,1,2};
        String [] names = {"Sue", "Bob", "Charlies"};
        
        // Class.forName("com.mysql.cj.jdbc.Driver");
        
        // Find the database
        String dbUrl = "jdbc:mysql://localhost:3306/people?serverTimeZone=UTC";
        var conn = DriverManager.getConnection(dbUrl, "root", "jupiter");
        
        System.out.println(conn);
        
        var stmt = conn.createStatement();
        conn.setAutoCommit(false);
        
        // Using insert or ignore instead of ignore, which is what the tutorial uses, to prevent sql errors if the program is run multiple times.
        String sql = "insert ignore into user (id, name) values(?, ?)";
        var insertStatement = conn.prepareStatement(sql);
        
        
        for (int i = 0; i < ids.length; i++) {
        	insertStatement.setInt(1, ids[i]);
        	insertStatement.setString(2, names[i]);
        	
        	insertStatement.execute();
        }
        
        conn.commit();
        insertStatement.close();

        sql = "select id, name from user";
        var rs = stmt.executeQuery(sql);
        
        while (rs.next()) {
        	int id = rs.getInt("id");
        	String name = rs.getString("name");
        	
        	System.out.println(id + ": " + name);
        }
        
        // Close open database resources
        stmt.close();        
        conn.close();
    }
}
