/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package application;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

public class App {
    public String getGreeting() {
        return "Hello World! from S05_T46-T51_SQLiteProject_IJ T47";
    }

    public static void main(String[] args) throws ClassNotFoundException, SQLException {
        System.out.println(new App().getGreeting());

        int [] ids = {0, 1, 2};
        String [] names = {"Sue", "Bob", "Charles"};

        Class.forName("org.sqlite.JDBC");

        String dbUrl ="jdbc:sqlite:people.db";
        var connection = DriverManager.getConnection(dbUrl);
        connection.setAutoCommit(false);

        System.out.println(connection);

        Statement stmt = connection.createStatement();
        String sql = "create table if not exists user(id integer primary key, name text not null)";
        stmt.execute(sql);

        sql = "insert or ignore into user(id, name) values(?, ?)";
        PreparedStatement insertStatement = connection.prepareStatement(sql);

        for (int i = 0; i < ids.length; i++) {
            insertStatement.setInt(1, ids[i]);
            insertStatement.setString(2, names[i]);

            insertStatement.execute();
        }

        connection.commit();
        insertStatement.close();

        sql = "select id, name from user";
        var rs = stmt.executeQuery(sql);

        while(rs.next()) {
            int id = rs.getInt("id");
            String name = rs.getString("name");
            System.out.println("id: " + id + ", " + "name: " + name);
        }

        sql = "drop table user";
        stmt.execute(sql);
        connection.commit();

        // Close open database resources
        stmt.close();
        connection.close();
    }
}
