/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.nio.charset.Charset;

import org.apache.commons.io.IOUtils;

import com.google.gson.Gson;

public class App {
    public String getGreeting() {
        return "Hello World! from S12_T139_A_JSON_Client";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        var url = "http://localhost:8080/S12_T138_Serving_JSON/users";
        
        try {
			var json = IOUtils.toString(new URL(url), Charset.forName("utf8"));
			
			Gson gson = new Gson();
			var users = gson.fromJson(json, User[].class);
			
			for (var user: users) {
				System.out.println(user);
			}
			
			System.out.println("\n");
	        System.out.println(json);
	        
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }
}
