/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

public class App {
    public String getGreeting() {
        return "Hello World! from S11_Swing_Demo";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
